#  Copyright (c) 2023, Circle Technologies, LLC. All rights reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

source 'https://cdn.cocoapods.org/'
source 'https://github.com/circlefin/w3s-ios-sdk.git'

platform :ios, '14.0'

target 'w3s-ios-sample-app-wallets' do
  # Use frameworks for dependencies
  use_frameworks! :linkage => :static

  # Add necessary pods
  pod 'CircleProgrammableWalletSDK'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  # Ensure proper Swift version
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end
